### ISSUE TITLE
Support for Quest 2 standalone / Sidequest / Macbook Air?

### ISSUE THREAD

**Issue by engagelively-galyleo** [Pokruk/CameraMod#2]
Hi,

I'm new to the Oculus, having recently acquired a Quest 2. We would like to install a simple Camera Mod directly to it using Sidequest or similar (we have a Macbook Air), but notice that perhaps this is complex and/or impossible as everything seems to be via Steamvr or other PC applications, can you advise whether it is possible to add this camera mod to the quest directly from our Mac? We have tried the bepinex route and it doesn't seem to like it, but any advice would be most appreciated.

Thanks in advance!

**Comment by Pokruk** [comment]
The support for standalone mods was removed from the game over a year ago. If support is returned, this issue may be reconsidered, but for now, the answer is 'no'.

**Comment by engagelively-galyleo** [comment]
Hi, my lad is over the moon that a camera mod is now available on standalone quest 2, is that just a coincidence? He also wanted to ask if it was still possible to request cosmetics for Gtag somewhere?

Thanks for your support
